import 'package:hive/hive.dart';
import '../services/core/logging_service.dart';
import 'video_display_item.dart';

part 'video_info.g.dart';

/// Audio quality tiers for merging video with audio
@HiveType(typeId: 3)
enum AudioQuality {
  @HiveField(0)
  high, // >160 kbps - Best quality, larger file
  @HiveField(1)
  mid, // 96-160 kbps - Balanced quality/size
  @HiveField(2)
  low, // <96 kbps - Smaller file size
}

/// Extension to provide audio quality utilities
extension AudioQualityExtension on AudioQuality {
  String get label {
    switch (this) {
      case AudioQuality.high:
        return 'High';
      case AudioQuality.mid:
        return 'Mid';
      case AudioQuality.low:
        return 'Low';
    }
  }

  String get ytdlpValue {
    switch (this) {
      case AudioQuality.high:
        return '0';
      case AudioQuality.mid:
        return '5';
      case AudioQuality.low:
        return '9';
    }
  }

  String get description {
    switch (this) {
      case AudioQuality.high:
        return 'Best quality (>160kbps)';
      case AudioQuality.mid:
        return 'Balanced (96-160kbps)';
      case AudioQuality.low:
        return 'Smaller file (<96kbps)';
    }
  }

  /// Check if a bitrate falls within this quality tier
  bool matchesBitrate(int? bitrate) {
    if (bitrate == null) {
      return this == AudioQuality.high; // Default to high if unknown
    }
    switch (this) {
      case AudioQuality.high:
        return bitrate > 160;
      case AudioQuality.mid:
        return bitrate >= 96 && bitrate <= 160;
      case AudioQuality.low:
        return bitrate < 96;
    }
  }
}

class SubtitleTrack {
  final String languageCode;
  final String name;
  final bool isAutoGenerated;
  final String? ext;

  SubtitleTrack({
    required this.languageCode,
    required this.name,
    this.isAutoGenerated = false,
    this.ext,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleTrack &&
          runtimeType == other.runtimeType &&
          languageCode == other.languageCode &&
          isAutoGenerated == other.isAutoGenerated;

  @override
  int get hashCode => languageCode.hashCode ^ isAutoGenerated.hashCode;
}

class VideoInfo with VideoDisplayItem {
  @override
  final String id;
  @override
  final String title;
  @override
  final String channel;
  final String channelUrl;
  @override
  final String thumbnailUrl;
  final int duration; // in seconds
  final String description;
  @override
  final int viewCount;
  @override
  final String uploadDate;
  final List<FormatInfo> formats;
  @override
  final String url;
  final List<SubtitleTrack> subtitles;

  // --- lazy caches for derived getters (VideoInfo is effectively immutable) ---
  List<FormatInfo>? _videoOnlyCached;
  List<FormatInfo>? _audioOnlyCached;
  List<FormatInfo>? _combinedCached;
  List<int>? _availableResolutionsCached;
  FormatInfo? _bestVideoFormatCached;
  bool _bestVideoFormatComputed = false;
  List<AudioQuality>? _availableAudioQualitiesCached;

  @override
  String get author => channel;

  @override
  int? get durationSeconds => duration;

  VideoInfo({
    required this.id,
    required this.title,
    required this.channel,
    required this.channelUrl,
    required this.thumbnailUrl,
    required this.duration,
    required this.description,
    required this.viewCount,
    required this.uploadDate,
    required this.formats,
    required this.url,
    required this.subtitles,
  });

  factory VideoInfo.fromJson(Map<String, dynamic> json) {
    final formatsList =
        (json['formats'] as List<dynamic>?)
            ?.map((f) => FormatInfo.fromJson(f as Map<String, dynamic>))
            .toList() ??
        [];

    // Single-pass debug stats: avoids 4 iterations over formatsList.
    int videoOnlyCount = 0;
    int audioOnlyCount = 0;
    int combinedCount = 0;
    final heightsSet = <int>{};
    for (final f in formatsList) {
      if (f.hasVideo && !f.hasAudio) {
        videoOnlyCount++;
      } else if (f.hasAudio && !f.hasVideo) {
        audioOnlyCount++;
      } else if (f.hasVideo && f.hasAudio) {
        combinedCount++;
      }
      if (f.hasVideo && f.height != null) {
        heightsSet.add(f.height!);
      }
    }
    LoggingService().debug(
      'Total formats received: ${formatsList.length}',
      component: 'VideoInfo',
    );
    LoggingService().debug(
      'Video-only: $videoOnlyCount, Audio-only: $audioOnlyCount, Combined: $combinedCount',
      component: 'VideoInfo',
    );
    final heights = heightsSet.toList()..sort((a, b) => b.compareTo(a));
    LoggingService().debug(
      'Available resolutions: ${heights.join(", ")}',
      component: 'VideoInfo',
    );

    final subsList = <SubtitleTrack>[];

    // Parse official subtitles
    if (json['subtitles'] != null && json['subtitles'] is Map) {
      final subsMap = json['subtitles'] as Map<String, dynamic>;
      subsMap.forEach((lang, details) {
        String name = lang;
        String? ext;
        if (details is List && details.isNotEmpty) {
          final detail = details.first as Map<String, dynamic>;
          name = detail['name'] ?? lang;
          ext = detail['ext'];
        }
        subsList.add(
          SubtitleTrack(
            languageCode: lang,
            name: name,
            isAutoGenerated: false,
            ext: ext,
          ),
        );
      });
    }

    // Parse auto-generated captions
    if (json['automatic_captions'] != null &&
        json['automatic_captions'] is Map) {
      final autoMap = json['automatic_captions'] as Map<String, dynamic>;
      autoMap.forEach((lang, details) {
        String name = lang;
        String? ext;
        if (details is List && details.isNotEmpty) {
          final detail = details.first as Map<String, dynamic>;
          name = detail['name'] ?? lang;
          ext = detail['ext'];
        }
        // Only add if not already present as official
        if (!subsList.any(
          (s) => s.languageCode == lang && !s.isAutoGenerated,
        )) {
          subsList.add(
            SubtitleTrack(
              languageCode: lang,
              name: '$name (Auto)',
              isAutoGenerated: true,
              ext: ext,
            ),
          );
        }
      });
    }

    // Sort: Official English first, then other official, then auto
    subsList.sort((a, b) {
      if (a.isAutoGenerated != b.isAutoGenerated) {
        return a.isAutoGenerated ? 1 : -1;
      }
      if (a.languageCode.startsWith('en') && !b.languageCode.startsWith('en')) {
        return -1;
      }
      if (!a.languageCode.startsWith('en') && b.languageCode.startsWith('en')) {
        return 1;
      }
      return a.name.compareTo(b.name);
    });

    return VideoInfo(
      id: json['id'] ?? '',
      title: json['title'] ?? 'Unknown Title',
      channel: json['channel'] ?? json['uploader'] ?? 'Unknown Channel',
      channelUrl: json['channel_url'] ?? json['uploader_url'] ?? '',
      thumbnailUrl: json['thumbnail'] ?? '',
      duration: json['duration']?.toInt() ?? 0,
      description: json['description'] ?? '',
      viewCount: json['view_count']?.toInt() ?? 0,
      uploadDate: json['upload_date'] ?? '',
      formats: formatsList,
      url: json['webpage_url'] ?? json['url'] ?? '',
      subtitles: subsList,
    );
  }

  /// Get best quality video+audio format — cached after first computation.
  FormatInfo? get bestVideoFormat {
    if (_bestVideoFormatComputed) return _bestVideoFormatCached;
    _bestVideoFormatComputed = true;
    final combined = combinedFormats;
    _bestVideoFormatCached = combined.isEmpty ? null : combined.first;
    return _bestVideoFormatCached;
  }

  /// Get video-only formats sorted by quality — lazy cached.
  List<FormatInfo> get videoOnlyFormats {
    final cached = _videoOnlyCached;
    if (cached != null) return cached;
    final videoFormats = formats
        .where((f) => f.hasVideo && !f.hasAudio)
        .toList();
    videoFormats.sort((a, b) => (b.height ?? 0).compareTo(a.height ?? 0));
    return _videoOnlyCached = List.unmodifiable(videoFormats);
  }

  /// Get audio-only formats sorted by quality — lazy cached.
  List<FormatInfo> get audioOnlyFormats {
    final cached = _audioOnlyCached;
    if (cached != null) return cached;
    final audioFormats = formats
        .where((f) => f.hasAudio && !f.hasVideo)
        .toList();
    audioFormats.sort(
      (a, b) => (b.audioBitrate ?? 0).compareTo(a.audioBitrate ?? 0),
    );
    return _audioOnlyCached = List.unmodifiable(audioFormats);
  }

  /// Get combined video+audio formats — lazy cached.
  List<FormatInfo> get combinedFormats {
    final cached = _combinedCached;
    if (cached != null) return cached;
    final combined = formats.where((f) => f.hasVideo && f.hasAudio).toList();
    combined.sort((a, b) => (b.height ?? 0).compareTo(a.height ?? 0));
    return _combinedCached = List.unmodifiable(combined);
  }

  /// Get all available resolutions (unique heights) — lazy cached.
  List<int> get availableResolutions {
    final cached = _availableResolutionsCached;
    if (cached != null) return cached;
    final heights = formats
        .where((f) => f.hasVideo && f.height != null)
        .map((f) => f.height!)
        .toSet()
        .toList();
    heights.sort((a, b) => b.compareTo(a));
    return _availableResolutionsCached = List.unmodifiable(heights);
  }

  @override
  String get formattedDuration {
    final hours = duration ~/ 3600;
    final minutes = (duration % 3600) ~/ 60;
    final seconds = duration % 60;

    if (hours > 0) {
      return '${hours.toString().padLeft(2, '0')}:${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
    }
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  String get formattedViewCount {
    if (viewCount >= 1000000000) {
      return '${(viewCount / 1000000000).toStringAsFixed(1)}B views';
    }
    if (viewCount >= 1000000) {
      return '${(viewCount / 1000000).toStringAsFixed(1)}M views';
    }
    if (viewCount >= 1000) {
      return '${(viewCount / 1000).toStringAsFixed(1)}K views';
    }
    return '$viewCount views';
  }

  /// Get audio formats filtered by quality tier
  List<FormatInfo> getAudioFormatsForQuality(AudioQuality quality) {
    final audioFormats = audioOnlyFormats;
    if (audioFormats.isEmpty) return [];

    // Filter by bitrate matching the quality tier
    final filtered = audioFormats
        .where((f) => quality.matchesBitrate(f.audioBitrate))
        .toList();

    // If no formats match the tier, return all available so user can still
    // select different codecs (Opus, AAC, MP3, etc.)
    if (filtered.isEmpty) {
      return audioFormats;
    }

    return filtered;
  }

  /// Get best audio format for a quality tier — avoids sorting via linear scan.
  FormatInfo? getBestAudioForQuality(AudioQuality quality) {
    final formats = getAudioFormatsForQuality(quality);
    if (formats.isEmpty) {
      final all = audioOnlyFormats;
      return all.isNotEmpty ? all.first : null;
    }
    // No need to sort filtered list (already in descending bitrate order
    // via audioOnlyFormats). Use linear scan to avoid O(n log n) sort.
    var best = formats.first;
    if (quality == AudioQuality.low) {
      for (final f in formats) {
        if ((f.audioBitrate ?? 0) < (best.audioBitrate ?? 0)) best = f;
      }
    } else {
      for (final f in formats) {
        if ((f.audioBitrate ?? 0) > (best.audioBitrate ?? 0)) best = f;
      }
    }
    return best;
  }

  /// Get available audio quality tiers for this video — lazy cached.
  List<AudioQuality> get availableAudioQualities {
    final cached = _availableAudioQualitiesCached;
    if (cached != null) return cached;
    final audioFormats = audioOnlyFormats;
    if (audioFormats.isEmpty) {
      return _availableAudioQualitiesCached =
          const [AudioQuality.high];
    }
    final qualities = <AudioQuality>[];
    for (final quality in AudioQuality.values) {
      if (audioFormats.any((f) => quality.matchesBitrate(f.audioBitrate))) {
        qualities.add(quality);
      }
    }
    if (qualities.isEmpty) qualities.add(AudioQuality.high);
    return _availableAudioQualitiesCached = List.unmodifiable(qualities);
  }

  /// Apply a HEAD-probed content-length to a format and clear derived caches.
  void applyProbedSize(String formatId, int bytes) {
    bool changed = false;
    for (int i = 0; i < formats.length; i++) {
      if (formats[i].formatId == formatId) {
        if (formats[i].filesize == bytes || formats[i].filesizeApprox == bytes) return;
        formats[i] = formats[i].copyWithProbedSize(bytes);
        changed = true;
        break;
      }
    }
    if (!changed) return;
    // Clear lazy caches so they recompute with probed size
    _videoOnlyCached = null;
    _audioOnlyCached = null;
    _combinedCached = null;
    _availableResolutionsCached = null;
    _bestVideoFormatCached = null;
    _bestVideoFormatComputed = false;
    _availableAudioQualitiesCached = null;
  }
}

class FormatInfo {
  final String formatId;
  final String? formatNote;
  final String? extension;
  final int? width;
  final int? height;
  final double? fps;
  final String? videoCodec;
  final String? audioCodec;
  final int? filesize;
  final int? filesizeApprox;
  final double? tbr; // total bitrate kbps (yt-dlp)
  final int? audioBitrate;
  final int? videoBitrate;
  final bool hasAudio;
  final bool hasVideo;
  final String? dynamicRange; // SDR, HDR, HDR10, etc.
  final int? sampleRate; // Audio sample rate
  final String? language; // Added for audio dubs
  final String? url; // Direct format URL for HEAD size probing (if yt-dlp provides it)

  FormatInfo({
    required this.formatId,
    this.formatNote,
    this.extension,
    this.width,
    this.height,
    this.fps,
    this.videoCodec,
    this.audioCodec,
    this.filesize,
    this.filesizeApprox,
    this.tbr,
    this.audioBitrate,
    this.videoBitrate,
    required this.hasAudio,
    required this.hasVideo,
    this.dynamicRange,
    this.sampleRate,
    this.language,
    this.url,
  });

  /// Copy with updated filesize (used for HEAD-probed size)
  FormatInfo copyWithProbedSize(int probedBytes) {
    return FormatInfo(
      formatId: formatId,
      formatNote: formatNote,
      extension: extension,
      width: width,
      height: height,
      fps: fps,
      videoCodec: videoCodec,
      audioCodec: audioCodec,
      filesize: filesize,
      filesizeApprox: filesizeApprox ?? probedBytes,
      tbr: tbr,
      audioBitrate: audioBitrate,
      videoBitrate: videoBitrate,
      hasAudio: hasAudio,
      hasVideo: hasVideo,
      dynamicRange: dynamicRange,
      sampleRate: sampleRate,
      language: language,
      url: url,
    );
  }

  factory FormatInfo.fromJson(Map<String, dynamic> json) {
    final vcodec = json['vcodec'];
    final acodec = json['acodec'];
    final hasVideo = _checkHasVideo(vcodec);
    final hasAudio = _checkHasAudio(acodec);

    return FormatInfo(
      formatId: json['format_id']?.toString() ?? '',
      formatNote: json['format_note']?.toString(),
      extension: json['ext']?.toString(),
      width: json['width']?.toInt(),
      height: json['height']?.toInt(),
      fps: json['fps']?.toDouble(),
      videoCodec: hasVideo ? vcodec?.toString() : null,
      audioCodec: hasAudio ? acodec?.toString() : null,
      filesize: json['filesize']?.toInt(),
      filesizeApprox: json['filesize_approx']?.toInt(),
      tbr: (json['tbr'] as num?)?.toDouble(),
      audioBitrate: json['abr']?.toInt(),
      videoBitrate: json['vbr']?.toInt(),
      hasAudio: hasAudio,
      hasVideo: hasVideo,
      dynamicRange: json['dynamic_range']?.toString(),
      sampleRate: json['asr']?.toInt(),
      language: json['language']?.toString(),
      url: json['url']?.toString(),
    );
  }

  /// Best known exact or approximate size from yt-dlp (prefers exact).
  int? get knownFilesize => filesize ?? filesizeApprox;

  /// True if this is an approximate size (filesize_approx or bitrate estimate), not exact filesize.
  bool get isApproximate => filesize == null && filesizeApprox != null;

  /// Estimate filesize in bytes using bitrate * duration.
  /// Falls back to heuristic bitrate if no bitrate present.
  /// Prefers exact filesize, then filesize_approx (approximate), then bitrate estimation.
  int? estimatedFilesize(int? durationSec) {
    // Prefer exact size
    if (filesize != null && filesize! > 0) return filesize;
    // Then approximate from yt-dlp
    if (filesizeApprox != null && filesizeApprox! > 0) return filesizeApprox;
    if (durationSec == null || durationSec <= 0) return null;

    double? kbps;
    // Prefer tbr (total), then codec-specific
    if (tbr != null && tbr! > 0) {
      kbps = tbr;
    } else if (hasVideo && hasAudio) {
      // combined but DASH rarely has combined; sum if both present
      final v = videoBitrate?.toDouble();
      final a = audioBitrate?.toDouble();
      if (v != null && a != null) {
        kbps = v + a;
      } else {
        kbps = v ?? a;
      }
    } else if (hasVideo) {
      kbps = videoBitrate?.toDouble();
    } else if (hasAudio) {
      kbps = audioBitrate?.toDouble();
    }

    // Heuristic fallback if still unknown
    kbps ??= _heuristicBitrateKbps();

    if (kbps == null || kbps <= 0) return null;
    // bytes = kbps * 1000 / 8 * duration
    return (kbps * 1000 / 8 * durationSec).round();
  }

  double? _heuristicBitrateKbps() => heuristicBitrateKbps;

  double? get heuristicBitrateKbps {
    // Rough YouTube averages. Ensures we rarely show "Unknown".
    if (hasAudio && !hasVideo) {
      // audio-only: assume bitrate from tier or 128k default
      if (audioBitrate != null && audioBitrate! > 0) return audioBitrate!.toDouble();
      return 128.0;
    }
    if (hasVideo) {
      final h = height;
      if (h == null) return null;
      // Adjust for fps: 60fps ~ 1.5x bitrate
      final fpsFactor = (fps != null && fps! >= 50) ? 1.5 : 1.0;
      double base;
      if (h >= 2160) {
        base = 14000;
      } else if (h >= 1440) {
        base = 8000;
      } else if (h >= 1080) {
        base = 4500;
      } else if (h >= 720) {
        base = 2500;
      } else if (h >= 480) {
        base = 1100;
      } else if (h >= 360) {
        base = 700;
      } else if (h >= 240) {
        base = 400;
      } else if (h >= 144) {
        base = 250;
      } else {
        base = 400;
      }
      // Modern codecs are more efficient: AV1 ~48% of H.264, VP9 ~60%, HEVC ~55%
      final codec = videoCodec?.toLowerCase() ?? '';
      if (codec.contains('av01') || codec.contains('av1')) {
        base *= 0.48;
      } else if (codec.contains('vp9') || codec.contains('vp09')) {
        base *= 0.60;
      } else if (codec.contains('hevc') || codec.contains('h265') || codec.contains('hvc1')) {
        base *= 0.55;
      }
      return base * fpsFactor;
    }
    return null;
  }

  /// Effective bitrate for sorting (tbr > vbr > heuristic)
  double? get effectiveBitrateKbps => tbr ?? videoBitrate?.toDouble() ?? heuristicBitrateKbps;

  /// Whether the size is an estimate (no exact filesize from yt-dlp)
  bool isEstimated(int? durationSec) => filesize == null && estimatedFilesize(durationSec) != null;

  /// Formatted size using estimate if needed. Returns '~12.3 MB' for estimated, exact otherwise.
  /// If duration unknown but bitrate known, falls back to bitrate display to avoid "Unknown size".
  String formattedEstimatedFilesize(int? durationSec) {
    final est = estimatedFilesize(durationSec);
    if (est != null) {
      final isEst = isEstimated(durationSec);
      final str = _formatBytes(est);
      return isEst ? '~$str' : str;
    }
    // Fallback: show bitrate when size cannot be computed (e.g. live / missing duration)
    final kbps = tbr ?? videoBitrate?.toDouble() ?? audioBitrate?.toDouble() ?? _heuristicBitrateKbps();
    if (kbps != null && kbps > 0) {
      if (kbps >= 1000) return '~${(kbps / 1000).toStringAsFixed(1)} Mbps';
      return '~${kbps.round()} kbps';
    }
    return 'Unknown size';
  }

  static String _formatBytes(int bytes) {
    if (bytes < 1024) return '$bytes B';
    if (bytes < 1024 * 1024) return '${(bytes / 1024).toStringAsFixed(1)} KB';
    if (bytes < 1024 * 1024 * 1024) return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
    return '${(bytes / (1024 * 1024 * 1024)).toStringAsFixed(2)} GB';
  }

  static bool _checkHasVideo(dynamic vcodec) {
    if (vcodec == null) return false;
    final str = vcodec.toString().trim().toLowerCase();
    if (str.isEmpty || str == 'none' || str == 'null') return false;
    return true;
  }

  static bool _checkHasAudio(dynamic acodec) {
    if (acodec == null) return false;
    final str = acodec.toString().trim().toLowerCase();
    if (str.isEmpty || str == 'none' || str == 'null') return false;
    return true;
  }

  String get displayName {
    final parts = <String>[];

    if (hasVideo && height != null) {
      parts.add('${height}p');
      if (fps != null && fps! > 30) {
        parts.add('${fps!.round()}fps');
      }
    }

    if (hasAudio && audioBitrate != null) {
      parts.add('${audioBitrate}kbps');
    }

    if (extension != null) {
      parts.add(extension!.toUpperCase());
    }

    return parts.join(' • ');
  }

  String get qualityLabel {
    if (height != null) {
      if (height! >= 2160) return '4K';
      if (height! >= 1440) return '2K';
      if (height! >= 1080) return 'Full HD';
      if (height! >= 720) return 'HD';
      return '${height}p';
    }
    if (audioBitrate != null) {
      return '${audioBitrate}kbps';
    }
    return formatNote ?? formatId;
  }

  String get formattedFilesize {
    final known = knownFilesize;
    if (known == null) return 'Unknown size';
    if (known < 1024) return '$known B';
    if (known < 1024 * 1024) return '${(known / 1024).toStringAsFixed(1)} KB';
    if (known < 1024 * 1024 * 1024) return '${(known / (1024 * 1024)).toStringAsFixed(1)} MB';
    return '${(known / (1024 * 1024 * 1024)).toStringAsFixed(2)} GB';
  }

  /// Check if this is an HDR format
  bool get isHdr {
    if (dynamicRange != null) {
      final dr = dynamicRange!.toLowerCase();
      return dr.contains('hdr') || dr.contains('hlg') || dr.contains('dv');
    }
    // Fallback: check format note
    if (formatNote != null) {
      final note = formatNote!.toLowerCase();
      return note.contains('hdr') ||
          note.contains('hlg') ||
          note.contains('dolby');
    }
    return false;
  }

  /// Check if this is a 60fps or higher format
  bool get is60fps => fps != null && fps! >= 60;

  /// Get a friendly codec name
  String get codecName {
    if (videoCodec == null || videoCodec == 'none') {
      if (audioCodec != null && audioCodec != 'none') {
        if (audioCodec!.contains('opus')) return 'Opus';
        if (audioCodec!.contains('mp4a') || audioCodec!.contains('aac')) {
          return 'AAC';
        }
        if (audioCodec!.contains('mp3')) return 'MP3';
        return audioCodec!.toUpperCase();
      }
      return 'Unknown';
    }
    if (videoCodec!.contains('av01') || videoCodec!.contains('av1')) {
      return 'AV1';
    }
    if (videoCodec!.contains('vp9') || videoCodec!.contains('vp09')) {
      return 'VP9';
    }
    if (videoCodec!.contains('avc') || videoCodec!.contains('h264')) {
      return 'H.264';
    }
    if (videoCodec!.contains('hevc') ||
        videoCodec!.contains('h265') ||
        videoCodec!.contains('hvc1')) {
      return 'H.265';
    }
    return videoCodec!.toUpperCase();
  }

  /// Get the audio quality tier for this format
  AudioQuality get audioQualityTier {
    if (audioBitrate == null) return AudioQuality.high;
    if (audioBitrate! > 160) return AudioQuality.high;
    if (audioBitrate! >= 96) return AudioQuality.mid;
    return AudioQuality.low;
  }
}
